name: Daily Auto Commit and Push

on:
  schedule:
    - cron: '0 0 * * *'   # Runs every day at midnight UTC
  workflow_dispatch:       # Allows manual trigger from the Actions tab

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

      # Optional: Example modification (you can replace this)
      - name: Make some changes
        run: |
          echo "Auto update on $(date -u '+%Y-%m-%d %H:%M:%S UTC')" > last-update.txt

      - name: Commit and push changes
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
          else
            git commit -m "Auto commit from GitHub Actions - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push origin HEAD:main
          fi
        shell: /usr/bin/bash -e {0}
